apiVersion: v1
kind: Service
metadata:
  name: movie-review-service
  namespace: playground
spec:
  type: NodePort
  selector:
    app: movie-review
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
      nodePort: 30002
